# Generated by Django 4.1.2 on 2022-11-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='link',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
