# Generated by Django 4.1.2 on 2022-11-16 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_entregables_estudiante'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Equipo',
        ),
    ]
