# Generated by Django 4.1.2 on 2022-11-16 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_rename_curso_equipo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Jugadores',
        ),
        migrations.RemoveField(
            model_name='entregables',
            name='estudiante',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='Entregables',
        ),
    ]
