# Generated by Django 4.1.2 on 2022-11-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_rename_estudiantes_jugadores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipo',
            name='camada',
        ),
        migrations.AddField(
            model_name='equipo',
            name='ciudad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
