# Generated by Django 4.1.2 on 2022-11-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_remove_equipo_camada_equipo_ciudad'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugadores',
            name='equipo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
