# Generated by Django 4.1.2 on 2022-11-16 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_jugadores_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='nacimiento',
            field=models.DateField(max_length=50, null=True),
        ),
    ]
